simplified public tests
drseg/swift-fsm pull request #2
Opened 2024-03-15 10:11 UTC by doozMen

I think it is important to test the public interface without the need for @testable

2024-03-16 19:42 UTC, drseg requested changes
Thank you very much for doing this. You are correct of course, and I would have saved myself some issues if I'd done this much earlier!

I've left a few comments as requests for changes just to make things match up with the rest of the project and then I'd be happy to put it in.

2024-03-16 19:42 UTC, drseg commented on Tests/SwiftFSMTests/FSMTests/SimplifiedPublicTests.swift
> +final class SimplifiedPublicTests: XCTestCase {
Change file and test class name to PublicInterfaceTests, to accompany some changes to other file names that I made in preparation for this (PublicTests -> PublicFSMTests, FSMTests -> InternalFSMTests).

2024-03-16 19:42 UTC, drseg commented on Tests/SwiftFSMTests/FSMTests/SimplifiedPublicTests.swift
> +    func lock() { lockCalled = true }
Inline the unlock() body

2024-03-16 19:42 UTC, drseg commented on Tests/SwiftFSMTests/FSMTests/SimplifiedPublicTests.swift
> +    XCTAssertTrue(sut.alarmCalled)
Add a blank line after each handleEvent()/XCTAssert... pair

2024-03-16 19:42 UTC, drseg commented on Tests/SwiftFSMTests/FSMTests/SimplifiedPublicTests.swift
Update indents to four spaces to match rest of project

2024-03-16 19:42 UTC, drseg commented on Tests/SwiftFSMTests/FSMTests/SimplifiedPublicTests.swift
> +final class SimplifiedPublicTests: XCTestCase {
(make sure to pull the latest changes from master first)

2024-03-20 09:29 UTC, doozMen commented on Tests/SwiftFSMTests/FSMTests/SimplifiedPublicTests.swift
> +    func lock() { lockCalled = true }
ok done

2024-03-20 09:30 UTC, doozMen commented on Tests/SwiftFSMTests/FSMTests/SimplifiedPublicTests.swift
oh yes my settings are different, keep forgetting that. Changed it!

2024-03-22 22:15 UTC, drseg approved these changes

2024-03-22 22:16 UTC, merged